Covid 19 info
Mucyosoda/covid-19-world-wide pull request #2
Opened 2022-02-01 09:57 UTC by Mucyosoda

**Covid19 app**  provides all information numerically in each country, the first-page displays all the countries, when you click on one country the other page with country info will display. the page had a search option where you can search by country name.
Countries and details are gotten and stored in the API.
App built in:
- React
- Redux
- JavaScript
- CSS
- Linter
- Baberlc
- API

2022-02-02 09:29 UTC, Meltrust requested changes
Hi @Mucyosoda, 


## Almost there! Keep it up!!!

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 09:29 UTC, Meltrust commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Kindly please make a video for this project., according to and following closely these requirements:


![image](https://user-images.githubusercontent.com/57421823/152125226-e758e5f8-0d7c-4f5a-b5c4-aede8baf912c.png)

- [ ] Let's give credit to this design's author! According to these instructions:


![image](https://user-images.githubusercontent.com/57421823/152125684-6fa7d8fd-c6a0-4bea-9fcb-ede03127b059.png)


- [ ] You need to please improve your readme.   Please kindly follow this [template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

That way, your app will be well documented 👍

2022-02-02 09:29 UTC, Meltrust commented on src/CSS/countryzz.css
> +
- [ ] Please, kindly correct this part on your homepage:


![image](https://user-images.githubusercontent.com/57421823/152126937-d1915f0b-8af0-4912-81e1-b6e8da8e7f7b.png)

As you can see, the elements are not centered, some of them contain an overflow.  
If you do this, your homepage will look striking! 💪

2022-02-03 16:08 UTC, AshakaE commented
### Hi @Mucyosoda   🙋‍♀️, 

# STATUS APPROVED ✔

Your:
   - Project is impressive 👏
   - Git flow ✔️ 
   - Pull request 👍 
   - README 👌 
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 16:15 UTC, merged